---
cf_tunnel_origin_request: {}

cloudflared_vars:
  kubernetes:
    image:
      tag: "2026.2.0"
    resources:
      limits:
        cpu:
        memory: 256Mi
      requests:
        cpu: 25m
        memory: 128Mi
    metrics:
      enable: true
      port: 20241
