---
cf_tunnel_origin_request: {}

cloudflared_vars:
  kubernetes:
    helm:
      chart:
        name: cloudflared
        version: v1.7.5
      repository:
        url: https://charts.kubito.dev
    resources:
      limits:
        cpu:
        memory: 256Mi
      requests:
        cpu: 25m
        memory: 128Mi
    metrics:
      enable: true
      port: 20241
