---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mosaic-face-detection-config
  namespace: mosaic-face-detection
  annotations:
    kubernetes.io/description: Non-sensitive application environment configuration values
data:
  SERVER_PORT: "40040"
  METRICS_PORT: "9092"
  MODELS_DIR: "models"
  REC_POOL_SIZE: "2"
  PROD_MODE: "false"