---
apiVersion: v1
kind: Service
metadata:
  name: face-detection-service
  namespace: mosaic-face-detection
  labels:
    app.kubernetes.io/name: mosaic-face-detection
  annotations:
    kubernetes.io/description: "Exposes an port for the pod for rest of cluster access to this service"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: mosaic-face-detection
  ports:
    - port: 9092
      targetPort: 9092
      protocol: TCP
      name: metrics
    - port: 40040
      targetPort: 40040
      protocol: TCP
      name: grpc
      appProtocol: kubernetes.io/h2c
