---
apiVersion: v1
kind: Secret
metadata:
  name: llm-api-key
  namespace: cyphria-data-pipeline
  annotations:
    kubernetes.io/description: LLM api key secret
type: Opaque
stringData:
  API_KEY: 

