---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Application related resources
  - application/deployment.yaml
  - application/configmap.yaml
  - application/service.yaml

  # secrets
  - secrets/llm.yaml

  # network policies (egress)
  - network-policy/egress-to-data.yaml
  - network-policy/egress-to-kube-dns.yaml
  - network-policy/egress-to-openai.yaml

  # network policies (ingress)
  - network-policy/ingress-from-airflow.yaml
