---
apiVersion: v1
kind: Service
metadata:
  name: cyphria-ranking-calculator-service
  annotations:
    kubernetes.io/description: "Exposes an port for the pod for rest of cluster access to this service"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: cyphria-ranking-calculator
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
