apiVersion: gateway.networking.k8s.io/v1
kind: GRPCRoute
metadata:
  name: face-detection-grpc
spec:
  parentRefs:
  - name: mosaic-gateway
  hostnames:
  - "face-detection.mosaic.com"
  rules:
  - backendRefs:
    - name: face-detection-service
      port: 40040