---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cyphria-insights-api-config
  annotations:
    kubernetes.io/description: Non-sensitive application environment configuration values
data:
  PRODUCTION_MODE: "true"
  FASTAPI_PORT: "8000"
  API_VERSION: "v1"
  # PostgreSQL connection details
  DB_HOST: "cyphria-postgres-cluster-rw.postgres.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "cyphria"
  # Valkey connection details
  CACHE_HOST: "valkey-master.valkey.svc.cluster.local"
  CACHE_PORT: "6379"
  MAX_CONNECTIONS: "10"
