---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: cyphria-data-ingestion-to-reddit-access
  namespace: cyphria-data-pipeline
  annotations:
    kubernetes.io/description: Allows calls to reddit for fetching data
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: cyphria-data-ingestion
      io.kubernetes.pod.namespace: cyphria-data-pipeline
  egress:
    - toFQDNs:
        - matchPattern: "*.reddit.com"
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
