---
- name: Role Facts
  ansible.builtin.include_role:
    name: "{{ role }}"
    tasks_from: facts
  loop:
    - networking/external_dns
    - networking/cilium
  loop_control:
    loop_var: role

- name: Include tunnel facts variables
  ansible.builtin.include_vars:
    file: "../../../../networking/cloudflare_tunnel/credentials/temp.yaml"

- name: Set Account ID Fact
  vars:
    cloudflare_env_data: "{{ lookup('ansible.builtin.template', 'env.yaml') | from_yaml }}"
  ansible.builtin.set_fact:
    api_key: "{{ cloudflare_env_data['cloudflare-token'] }}"
    email: "{{ cloudflare_env_data['email'] }}"
    zone_id: "{{ cloudflare_env_data['zone-id'] }}"

- name: Create namespaces
  kubernetes.core.k8s:
    state: present
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    definition:
      - apiVersion: v1
        kind: Namespace
        metadata:
          name: frontend

- name: Deploy frontend crds (deployment, service, hpa, network-policies)
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('ansible.builtin.template', 'deploy_crds.yaml') | from_yaml }}"
    kubeconfig: /etc/rancher/k3s/k3s.yaml

- name: Deploy DNS Endpoint for external-dns
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('ansible.builtin.template', 'dns-endpoint.j2') | from_yaml }}"
    kubeconfig: /etc/rancher/k3s/k3s.yaml
