---
- name: Uninstall insights api application in argocd
  kubernetes.core.k8s:
    api_version: argoproj.io/v1alpha1
    state: absent
    kind: Application
    name: cyphria-insights-api
    namespace: argocd
