---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloudflare-tunnel-mosaic

resources:
  - application/deployment.yaml
  - application/service.yaml

  - network-policy/egress-to-mosaic.yaml