---
apiVersion: v1
kind: Service
metadata:
  name: cloudflared-mosaic-metrics
  labels:
    app: cloudflared-mosaic
spec:
  selector: 
    app: cloudflared-mosaic
  ports:
    - name: metrics
      protocol: TCP
      port: 20241
      targetPort: 20241