---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cyphria-postgres-cluster
  annotations:
    kubernetes.io/description: cluster yaml file to bootstrap cnpg cluster for cyphria
spec:
  instances: 1
  # Database PVC (HDD)
  storage:
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Ti
      storageClassName: local-storage
      volumeMode: Filesystem
  # WAL PVC (SSD)
  walStorage:
    pvcTemplate:
      accessModes:
        - "ReadWriteOnce"
      resources:
        requests:
          storage: 100Gi
      storageClassName: local-path
      volumeMode: Filesystem
  # Creating the database with the user secret
  bootstrap:
    initdb:
      database: cyphria
      owner: cyphria_user
      postInitApplicationSQLRefs:
        configMapRefs:
          - name: cyphria-init-schema
            key: schema.sql

  postgresql:
    # only allow connections over ssl/tls, to cyphria database,
    # from the ip range, and using password authentication
    pg_hba:
      - hostssl cyphria cyphria_user 10.0.0.0/16 scram-sha-256
    parameters:
      max_wal_size: "4GB"
      max_wal_senders: "3"
      wal_level: "replica"

  resources:
    limits:
      memory: 7G
    requests:
      cpu: "1"
      memory: 1G

  monitoring:
    enablePodMonitor: true
