apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # network policies (egress)
  - network-policy/egress-to-cyphria.yaml
  - network-policy/egress-to-data.yaml
  - network-policy/egress-to-kube-dns.yaml

