---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: mosaic-cloudflare-tunnel-from-vm-access
  namespace: cloudflare-tunnel-mosaic
spec:
  endpointSelector: {}
  ingress:
    # Prometheus metrics
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: victoria-metrics
      toPorts:
        - ports:
            - port: "20241"
              protocol: TCP
