---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - database/cluster_config.yaml
  - database/credentials.yaml
  - database/schema.yaml
  - database/storage-class.yaml
  - database/persistent-volume.yaml

  - networking/grpc-gateway.yaml
  
  - platform/tls-cert.yaml