---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cache/connection_url_secret.yaml
  
  - database/cluster_config.yaml
  - database/schema.yaml
  - database/storage-class.yaml
  - database/persistent-volume.yaml

  - gateway.yaml