---
apiVersion: v1
kind: Secret
metadata:
  name: reddit-api-connection-secret
  namespace: cyphria-data-pipeline
  annotations:
    kubernetes.io/description: Reddit api client connection credentials secret
type: Opaque
stringData:
  REDDIT_API_CLIENT_ID: 
  REDDIT_API_CLIENT_SECRET:
  REDDIT_ACCOUNT_USERNAME:
  REDDIT_ACCOUNT_PASSWORD:
